SELECT [Charge_Code_Package]
      ,[Gross_Charges]
      ,[Charge_Description]
      ,[Patient_Type]
      ,[Rev_Code]
      ,[Discounted_Cash_Price]
      ,[De_Identified_Minimum]
      ,[De_Identified_Maximum]
  FROM [dbo].[TuomeyHospital_standardcharges - Output]